<script setup lang="ts">
import {
  RefreshCw,
  ShieldCheck,
  Award,
  Activity,
  Database,
  Folder,
  Clock4,
  CheckCircle2,
  XCircle,
  Inbox,
  AlertTriangle,
  FileText,
  FileUp,
  Box,
  CheckCircle,
  LineChart,
  Database as DatabaseIcon,
  FileSearch,
  ArrowLeft,
  FileX,
  Inbox as InboxIcon,
  Sparkles,
  Search,
  Send,
  StopCircle,
  Trash2,
  Settings,
  BarChart3,
  Layers,
  Network,
  RotateCw,
  Download,
  Copy,
  Check,
  ChevronRight,
  X,
  FilePlus,
  Plane,
} from "lucide-vue-next";

const props = defineProps<{
  name: string;
  class?: string;
}>();

const map: Record<string, any> = {
  "refresh-cw": RefreshCw,
  "shield-check": ShieldCheck,
  award: Award,
  activity: Activity,
  database: Database,
  folder: Folder,
  clock: Clock4,
  "check-circle": CheckCircle2,
  "x-circle": XCircle,
  inbox: Inbox,
  "alert-triangle": AlertTriangle,
  "file-text": FileText,
  "file-up": FileUp,
  box: Box,
  check: CheckCircle,
  "line-chart": LineChart,
  "database-icon": DatabaseIcon,
  "file-search": FileSearch,
  "arrow-left": ArrowLeft,
  "file-x": FileX,
  "inbox-icon": InboxIcon,
  sparkles: Sparkles,
  search: Search,
  send: Send,
  "stop-circle": StopCircle,
  trash: Trash2,
  settings: Settings,
  "bar-chart-3": BarChart3,
  layers: Layers,
  network: Network,
  "rotate-cw": RotateCw,
  download: Download,
  copy: Copy,
  check2: Check,
  "chevron-right": ChevronRight,
  x: X,
  "file-plus": FilePlus,
  plane: Plane,
};
</script>

<template>
  <component :is="map[props.name] || FileText" :class="props.class" />
</template>
